name: port_casa
description: "Application de gestion des anomalies - Port de Casablanca"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  cloud_firestore: ^5.0.0
  firebase_storage: ^12.0.0
  firebase_messaging: ^15.0.0
  
  # UI & Charts
  google_fonts: ^6.2.1
  fl_chart: ^0.69.0
  
  # State Management
  provider: ^6.1.2
  
  # Image Picker
  image_picker: ^1.1.2
  
  # Icons
  cupertino_icons: ^1.0.8
  
  # Utils
  intl: ^0.19.0
  uuid: ^4.5.1
  cached_network_image: ^3.4.1
  
  # Offline Support
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
